spring:
  application:
    name: reportes

datasource:
  driver : org.postgresql.Driver
  url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
  username: ${DB_USERNAME:compose-postgres}
  password: ${DB_PASSWORD:compose-postgres}